AGENT_PRIVATE_KEY = ****----\n
FLAG1 = 06165DF2-C047-4402-8CAB-1C8EC526C115
GITEA_ACCESS_TOKEN = ****9b68
FLAG8 = B1A648E1-FD8B-4D66-8CAF-78114F55D396
ADMIN_PASSWORD = CHANGE_ME_ADMIN_PASSWORD
ALICE_PASSWORD = CHANGE_ME_ALICE_PASSWORD
KNAVE_PASSWORD = CHANGE_ME_KNAVE_PASSWORD